'use strict';

const copy = {
  en: { connection:'Operations', simulation:'n8n connected', eyebrow:'N8N-ORCHESTRATED OPERATIONS', demoNotice:'Cases are processed by n8n and stored for operational review.', title:'Turn unstructured requests into accountable operations cases.', lede:'n8n and Gemini classify each request; deterministic policy controls escalation and operators retain the final decision.', incoming:'Incoming request', synthetic:'Synthetic data only', requestLabel:'What does the operations team need to resolve?', tryExample:'Try an example', accessExample:'Repository access', billingExample:'Incorrect invoice', technicalExample:'Service unavailable', analyze:'Create case', caseAnalysis:'Case analysis', empty:'Submit a request to create and inspect a case.', processing:'Creating case…', category:'Category', priority:'Priority', review:'Human review', engine:'Decision engine', summary:'Operational summary', nextAction:'Next action', missing:'Missing information', retrievedProcedure:'Retrieved procedure', auditTrail:'Audit trail', errorTitle:'The request could not be processed.', boundedTitle:'Bounded decisions', boundedText:'Deterministic rules control sensitive actions and escalation.', evidenceTitle:'Visible evidence', evidenceText:'Every recommendation identifies its supporting procedure.', fallbackTitle:'Operational control', fallbackText:'Cases requiring review remain pending until an operator decides.', yes:'Required', no:'Not required', none:'None', placeholder:'Example: I cannot access the analytics repository and I need to deliver a change today.', queue:'Operations queue', operatorKey:'Operator key', unlock:'Open queue', refresh:'Refresh', all:'All', pending:'Pending', approve:'Approve', reject:'Reject', note:'Decision note', noCases:'No cases found.', unauthorized:'Invalid operator key.', status:'Status', created:'Created' },
  es: { connection:'Operaciones', simulation:'n8n conectado', eyebrow:'OPERACIONES ORQUESTADAS CON N8N', demoNotice:'Los casos son procesados por n8n y guardados para revisión operativa.', title:'Convertí solicitudes desestructuradas en casos operativos responsables.', lede:'n8n y Gemini clasifican cada solicitud; una política determinista controla el escalamiento y los operadores conservan la decisión final.', incoming:'Solicitud recibida', synthetic:'Solo datos ficticios', requestLabel:'¿Qué necesita resolver el equipo de operaciones?', tryExample:'Probar un ejemplo', accessExample:'Acceso a repositorio', billingExample:'Factura incorrecta', technicalExample:'Servicio no disponible', analyze:'Crear caso', caseAnalysis:'Análisis del caso', empty:'Enviá una solicitud para crear e inspeccionar un caso.', processing:'Creando caso…', category:'Categoría', priority:'Prioridad', review:'Revisión humana', engine:'Motor de decisión', summary:'Resumen operativo', nextAction:'Próxima acción', missing:'Información faltante', retrievedProcedure:'Procedimiento recuperado', auditTrail:'Registro de auditoría', errorTitle:'No se pudo procesar la solicitud.', boundedTitle:'Decisiones limitadas', boundedText:'Las reglas deterministas controlan acciones sensibles y escalamiento.', evidenceTitle:'Evidencia visible', evidenceText:'Cada recomendación identifica el procedimiento que la fundamenta.', fallbackTitle:'Control operativo', fallbackText:'Los casos que requieren revisión siguen pendientes hasta que decide un operador.', yes:'Requerida', no:'No requerida', none:'Ninguna', placeholder:'Ejemplo: No puedo acceder al repositorio de analítica y necesito entregar un cambio hoy.', queue:'Bandeja de operaciones', operatorKey:'Clave de operador', unlock:'Abrir bandeja', refresh:'Actualizar', all:'Todos', pending:'Pendientes', approve:'Aprobar', reject:'Rechazar', note:'Nota de decisión', noCases:'No se encontraron casos.', unauthorized:'Clave de operador inválida.', status:'Estado', created:'Creado' }
};
const examples = {
  en:{access:'I cannot access the analytics repository and I need to deliver a change today.',billing:'Invoice INV-204 has an incorrect amount of USD 480.',technical:'The client portal service is unavailable for the whole support team.'},
  es:{access:'No puedo acceder al repositorio de analítica y necesito entregar un cambio hoy.',billing:'La factura INV-204 tiene un importe incorrecto de USD 480.',technical:'El servicio del portal de clientes no está disponible para todo el equipo de soporte.'}
};
const savedLanguage=localStorage.getItem('ops-language');
let language=savedLanguage==='es'||savedLanguage==='en'?savedLanguage:((navigator.language||'').toLowerCase().startsWith('es')?'es':'en'), theme=localStorage.getItem('ops-theme')||(matchMedia?.('(prefers-color-scheme: dark)').matches?'dark':'light');
let operatorKey=sessionStorage.getItem('ops-operator-key')||'', currentFilter='all';
const ids=['triageForm','requestText','resultPanel','emptyState','loadingState','resultContent','errorState','errorMessage','caseId','category','priority','review','engine','summary','nextAction','missing','sourceTitle','sourceExcerpt','sourceId','auditTrail','themeButton','languageButton','connectionButton','modeLabel','queueSection','operatorForm','operatorKey','queueContent','caseList','queueMessage','refreshCases','filterAll','filterPending'];
const el=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
function applyTheme(){document.documentElement.dataset.theme=theme;el.themeButton.setAttribute('aria-pressed',String(theme==='dark'));el.themeButton.textContent=theme==='dark'?'☼':'◐';}
function applyLanguage(){const c=copy[language];document.documentElement.lang=language;document.querySelectorAll('[data-i18n]').forEach(n=>{if(c[n.dataset.i18n])n.textContent=c[n.dataset.i18n];});el.requestText.placeholder=c.placeholder;el.languageButton.textContent=language==='en'?'ES':'EN';}
function setView(view){['emptyState','loadingState','resultContent','errorState'].forEach(k=>{el[k].hidden=k!==view;});el.resultPanel.setAttribute('aria-busy',view==='loadingState'?'true':'false');}
async function api(url,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(operatorKey)headers['X-Operator-Key']=operatorKey;const response=await fetch(url,{...options,headers});const body=await response.json();if(!response.ok)throw Object.assign(new Error(body.error||`HTTP ${response.status}`),{status:response.status});return body;}
function render(result){const c=copy[language];el.caseId.textContent=result.caseId;el.category.textContent=result.category;el.priority.textContent=result.priority;el.review.textContent=result.humanReview?c.yes:c.no;el.engine.textContent=result.engine;el.summary.textContent=result.summary;el.nextAction.textContent=result.nextAction;el.missing.replaceChildren(...(result.missing.length?result.missing:[c.none]).map(x=>Object.assign(document.createElement('span'),{textContent:x})));el.sourceTitle.textContent=result.procedure.title;el.sourceExcerpt.textContent=result.procedure.excerpt;el.sourceId.textContent=result.procedure.id;el.auditTrail.replaceChildren(...result.audit.map(x=>Object.assign(document.createElement('li'),{textContent:x})));setView('resultContent');}
el.triageForm.addEventListener('submit',async event=>{event.preventDefault();setView('loadingState');el.caseId.textContent='ROUTING';try{const result=await api('/api/triage',{method:'POST',body:JSON.stringify({request:el.requestText.value})});render(result);if(operatorKey)await loadCases();}catch(error){el.caseId.textContent='ERROR';el.errorMessage.textContent=error.message;setView('errorState');}});
document.querySelectorAll('[data-example]').forEach(button=>button.addEventListener('click',()=>{el.requestText.value=examples[language][button.dataset.example];el.requestText.focus();}));
el.languageButton.addEventListener('click',()=>{language=language==='en'?'es':'en';localStorage.setItem('ops-language',language);applyLanguage();if(operatorKey)loadCases();});
el.themeButton.addEventListener('click',()=>{theme=theme==='dark'?'light':'dark';localStorage.setItem('ops-theme',theme);applyTheme();});
el.connectionButton.addEventListener('click',()=>{el.queueSection.scrollIntoView({behavior:'smooth'});el.operatorKey.focus();});
el.operatorForm.addEventListener('submit',async event=>{event.preventDefault();operatorKey=el.operatorKey.value;sessionStorage.setItem('ops-operator-key',operatorKey);await loadCases();});
el.refreshCases.addEventListener('click',loadCases);el.filterAll.addEventListener('click',()=>{currentFilter='all';loadCases();});el.filterPending.addEventListener('click',()=>{currentFilter='pending_review';loadCases();});
async function loadCases(){try{const data=await api(`/api/cases?status=${encodeURIComponent(currentFilter)}`);el.queueContent.hidden=false;el.queueMessage.textContent='';renderCases(data.cases);}catch(error){el.queueContent.hidden=true;el.queueMessage.textContent=error.status===401?copy[language].unauthorized:error.message;}}
function renderCases(cases){const c=copy[language];if(!cases.length){el.caseList.replaceChildren(Object.assign(document.createElement('p'),{textContent:c.noCases}));return;}el.caseList.replaceChildren(...cases.map(item=>{const card=document.createElement('article');card.className='case-card';const head=document.createElement('div');head.className='case-card-head';const title=document.createElement('strong');title.textContent=`${item.caseId} · ${item.category}`;const badge=document.createElement('span');badge.className=`case-status status-${item.status}`;badge.textContent=item.status.replace('_',' ');head.append(title,badge);const request=document.createElement('p');request.textContent=item.request;const meta=document.createElement('small');meta.textContent=`${c.created}: ${new Date(item.createdAt).toLocaleString(language)} · ${item.priority}`;card.append(head,request,meta);if(item.status==='pending_review'){const note=document.createElement('input');note.placeholder=c.note;note.maxLength=1000;const actions=document.createElement('div');actions.className='case-actions';for(const [decision,label] of [['approve',c.approve],['reject',c.reject]]){const button=document.createElement('button');button.type='button';button.className=decision==='approve'?'primary-button':'secondary-button';button.textContent=label;button.addEventListener('click',async()=>{button.disabled=true;try{await api(`/api/cases/${item.id}/decision`,{method:'POST',body:JSON.stringify({decision,note:note.value})});await loadCases();}catch(error){el.queueMessage.textContent=error.message;}finally{button.disabled=false;}});actions.append(button);}card.append(note,actions);}else if(item.decisionNote){const note=document.createElement('p');note.className='decision-note';note.textContent=item.decisionNote;card.append(note);}return card;}));}
el.operatorKey.value=operatorKey;applyTheme();applyLanguage();if(operatorKey)loadCases();
